[pytest]
testpaths = tests
python_files = test_*.py
pythonpath = .
addopts =
    --cov=custom_components/ebay
    --cov-report=term-missing
    --cov-fail-under=80

[coverage:run]
branch = False
source = custom_components/ebay

[coverage:report]
show_missing = True
skip_covered = False
